### ISSUE TITLE
PyPy Support

### ISSUE THREAD

**Issue by alex-chan** [montag451/pytun#11] opened 2016-08-09 02:16 UTC
PyPy is a python implemention for python, which implemented JIT that can largely speed up the execution.

After I installed python-pytun for pypy and trying to use it, I got a `import error`

```
pypy -m pip install python-pytun
```

```
xxx-VirtualBox# pypy
Python 2.7.10 (5.3.1+dfsg-1~ppa1~ubuntu16.04, Jun 19 2016, 15:11:31)
[PyPy 5.3.1 with GCC 5.3.1 20160413] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> import pytun
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named pytun
```

Note: A file named `pytun.pypy-41.so` in dist-pakcages directory

**Comment by montag451** [comment] 2016-08-09 16:18
Strange because it is working on my system with PyPy 5.3.1:
![pypy](https://cloud.githubusercontent.com/assets/249317/17524142/9eb09ff4-5e5d-11e6-9d9e-88089c9b09fb.png)

**Comment by alex-chan** [comment] 2016-08-10 02:29
OK, I'll try it again~

**Comment by alex-chan** [comment] 2016-08-10 11:10
It's quite strange that if I install and import it under non-root account, I can import it without errors

But if I install it under non-root account, and import it under root account, It prompts can not find the `pytun`. Meanwhile, `twisted` is OK on this situation.

I can not install it under root account, a compile error throw out says 'can not find Python.h', however, I installed `python-dev` via `apt-get`

It's very interesting..

**Comment by montag451** [comment] 2016-12-11 15:10
I will close this issue because I can't reproduce it and it seems related to your setup.

**Closed by montag451** 2016-12-11 15:10 UTC
